
ALTER TABLE item
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=216;

ALTER TABLE sellers
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

ALTER TABLE wskazniki
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=747;
COMMIT;
