INSERT INTO sellers (ID, Seller_name) VALUES
(0, 'Test'),
(1, 'PIVOT CAR ELECTRICAL PARTS'),
(2, 'HANSSENTUNE Racing Store'),
(3, 'LZONE PERFORMANCE Store'),
(4, 'HUBsport DE Store'),
(5, 'Performance Tuning Parts Store'),
(6, 'Car Top ACE Store'),
(7, 'REPLAITZ Store'),
(8, 'EPMAN Racing Store'),
(9, 'PQY RACING Store'),
(10, 'banwinoto Official Store'),
(11, 'Minespeed Store'),
(12, 'TOSPORT RACING Store'),
(13, 'WLR racing Store'),
(14, 'WarmHome Store'),
(15, 'MaxPeedingRods - official from webpage'),
(16, 'TeamOne Store'),
(17, 'CoCo Car Parts'),
(18, 'Awesome for you store'),
(19, 'Kris Store'),
(20, 'ToTop Store'),
(21, 'FlyingCar Store'),
(22, 'S-life Store'),
(23, 'mustang Store'),
(24, 'AUTOFAB Racing Parts Store'),
(25, 'Motor vehiclepart');
INSERT INTO item (ID, Name) VALUES
(1, 'ADDCO BOOST'),
(2, 'ADDCO OilPressure'),
(3, 'ADDCO OilTemp'),
(4, 'ADDCO EGT'),
(5, 'ADDCO AFR'),
(6, 'ADDCO WaterTemp'),
(10, 'DEFI Boost'),
(11, 'DEFI OilPressure'),
(12, 'DEFI OilTemp'),
(13, 'DEFI EGT'),
(14, 'DEFI Water Temp'),
(15, 'VDO Oil Temp Gauge wskaznik'),
(16, 'VDO Oil Pressure Gauge wskaznik'),
(17, 'VDO Water Temp Gauge wskaznik'),
(20, 'Greddy Boost'),
(21, 'Greddy OilPressure'),
(22, 'Greddy OilTemp'),
(23, 'Greddy EGT'),
(30, 'Nakladki 4 x BREMBO Red'),
(31, 'Nakladki 4 x BREMBO Blue'),
(32, 'Nakladki 4 x BREMBO Yellow'),
(33, 'Nakladki 4 x BREMBO Gold'),
(39, 'Tasma zlota 5m odbijajaca cieplo termiczna'),
(40, 'Control arms BMW E36 E46 wahacze regul Maxpeedingrods 2szt'),
(41, 'Plates E36 Camber plates Maxpeedingroods 2szt.'),
(42, 'Zawieszenie gwintowane E39 bez regul'),
(43, 'Zawieszenie gwintowane E36 z regulacja'),
(44, 'Zawieszenie gwintowane BMW E36 BEZ regul'),
(45, 'Zawieszenie gwintowane E46 z regulacja'),
(46, 'Zawieszenie gwintowane BMW E46 BEZ regul'),
(47, 'Zawieszenie gwintowane Subaru Impreza GDB 00-05'),
(48, 'Zawieszenie gwintowane E60 BMW'),
(49, 'Plates E46 Camber plates Maxpeedingroods 2szt.'),
(50, 'Lotki male 4 szt.'),
(51, 'Lotki duze 6 szt.'),
(52, 'Lotki plaskie plastik 4 szt.'),
(53, 'Lotki duze 6 szt. - czarne'),
(54, 'Lotki plaskie CARBON 4 szt.'),
(55, 'Lotki, spliterry 2szt dolne na zderzak'),
(59, 'Poszerzenia blotnikow nadkoli 4szt.'),
(60, 'Blow Off 1.8t'),
(61, 'Adaptery skretu BMW E36 black'),
(62, 'Regulator sily hamowania korektor'),
(64, 'Blow Off 1.8t - NIE Hybrydowy'),
(65, 'Adaptery skretu E46 BMW black e46'),
(70, 'Obudowa plaska potrojna 3x52mm'),
(71, 'Obudowa na slupek potrojna 3x52mm'),
(72, 'Obudowa potrojna stojaca 3x52mm'),
(80, 'MP3 AUX USB Adapter 8PIN'),
(90, 'Podstawka pod filtr oleju'),
(95, 'Akrapovic koncowka wydechu 60mm x 89mm matowa'),
(96, 'Akrapovic koncowka wydechu 63mm x 89mm matowa'),
(97, 'Akrapovic koncowka wydechu 63mm x 101mm matowa'),
(98, 'Dystans 5mm'),
(99, 'Daszek maly 52mm'),
(100, 'OilPressure sensor czujnik'),
(101, 'Boost sensor czujnik map'),
(102, 'EGT sensor czujnik termopara'),
(109, 'Trojnik M12x1.5 x 1/8NPT'),
(110, 'Adapter do turbo wezyk Quick tap'),
(140, 'Zawieszenie gwintowane Lexus IS200 IS300'),
(141, 'Zawieszenie gwintowane Honda Civic regulowane'),
(142, 'Zawieszenie gwintowane Subaru Impreza GC8 bez reg.'),
(143, 'Zawieszenie gwintowane Honda Accord bez regul'),
(144, 'Zawieszenie gwintowane Mazda MX5 regulowane'),
(145, 'Zawieszenie gwintowane Mazda MX5 BEZ REGULacji'),
(200, 'Zawieszenie gwintowane przod bez camberow E36'),
(201, 'Zawieszenie gwintowane przod KPL z camber E36'),
(202, 'Zawieszenie gwintowane tyl KPL z camber E36'),
(203, 'Sprezyny tyl z nakretkami E36'),
(210, 'Zawieszenie przod bez camber e46'),
(211, 'Zawieszenie przod KPL z camber e46'),
(212, 'Zawieszenie tyl KPL z camber bez spr e46'),
(215, 'Sprezyny tyl z nakretkami E46');